config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  
  resources :users, except: [:new]
  
  resources :user_stocks, except: [:show, :edit, :update]
  
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  get 'search_stocks' => 'stocks#search'
  
  get 'stocks' => 'stocks#index'
  
  resources :stocks, only: [:show]
  
  get 'friends' => 'users#friends'
  
  resources :friendships, only: [:new, :create, :destroy]
  
  post 'add_friend' => 'users#add_friend'
  
  get 'search_friends' => 'users#search'
  

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

end

app/models/stock.rb
class Stock < ActiveRecord::Base

  has_many :user_stocks
  has_many :users, through: :user_stocks
  
  validates :ticker, uniqueness: true

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
  
  def self.new_from_lookup(ticker_symbol)
    return nil unless StockQuote::Stock.quote(ticker_symbol).name
    new_stock=new(ticker: ticker_symbol,
                  name: StockQuote::Stock.quote(ticker_symbol).name)
    new_stock.last_price=new_stock.price
    new_stock
  end
  
  def price
    return StockQuote::Stock.quote(ticker).close if StockQuote::Stock.quote(ticker).close
    return StockQuote::Stock.quote(ticker).previous_close if StockQuote::Stock.quote(ticker).previous_close
    "Unavailable"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  
  has_secure_password
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6, maximum: 25 }
  
  def self.search(param)
    return User.none if param.blank?
    
    param.strip!
    param.downcase!
    (first_name_matches(param)+last_name_matches(param)+email_matches(param))
  
  end
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end
  
end

app/models/user_stock.rb
class UserStock < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :current_user, :logged_in?, :require_user

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
  !!current_user
end

def require_user
  if !logged_in?
  flash[:danger]="You must be logged in to proceed"
  redirect_to login_path
  end
end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def destroy
    @friendship=Friendship.find(params[:id])
    @friendship.destroy
    flash[:success]="You are no longer following this person"
    redirect_to user_path(current_user)
  end
  
  def create
    @friendship=Friendship.new(user_id: current_user.id, friend_id: params[:friend_id])
    @friendship.save
    flash[:success]="Now following this person"
    redirect_to user_path(current_user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController
  def new
    
  end
  
  def create
    user=User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      flash[:notice]="You are now logged in"
      redirect_to user_path(user)
    else
      flash[:notice]="Please check your details and try again"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id]=nil
    flash[:notice]="You have successfully logged out"
    redirect_to root_path
  end
  
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      @stock ||= Stock.new_from_lookup(params[:stock])
    end
      
    if @stock
      #render json: @stock
      render partial: 'lookup'
    else 
      render status: :not_found, nothing: true
    end
    
  end
  
  def index
    @stocks=Stock.all
  end
  
  def show
    @stock=Stock.find(params[:id])
    @user_stock = current_user.user_stocks.find_by(stock_id: params[:id])
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController


  def new
    @user_stock=UserStock.new
  end
  
  def create
    if params[:stock_id].present?
      @user_stock=UserStock.new(user: current_user, stock_id: params[:stock_id])
    else
      if Stock.find_by_ticker(params[:stock_ticker])
        @user_stock=UserStock.new(user: current_user, 
                          stock: Stock.find_by_ticker(params[:stock_ticker]))
      else 
        if Stock.new_from_lookup(params[:stock_ticker]).save
          @user_stock=UserStock.new(user: current_user, 
                          stock: Stock.new_from_lookup(params[:stock_ticker]))
        else
          @user_stock= nil
          flash[:danger]="Stock Unavailable"
        end    
      end
    end
    
    if @user_stock.save
      flash[:success]="You are now tracking this stock"
      redirect_to user_path(current_user)
    else
      flash[:danger]="Please check and try again"
      render 'new'
    end
      
  end
  
  def index
    @user_stocks=UserStock.all
  end
  
  def destroy
      @user_stock=UserStock.find(params[:id])
      @user_stock.destroy
      flash[:success]="No longer following this stock"
      redirect_to user_path(current_user)
  end
  
  def show
    #@user_stock=UserStock.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :require_same_user, only: [:edit, :update]
  
  def new
    @user=User.new 
  end
  
  def create
    @user=User.new(user_params)
    if @user.save
      flash[:notice]="Welcome to Stock Tracker"
      session[:user_id]=@user.id
      redirect_to user_path(@user)
    else
      flash[:notice]="Please check your details"
      render 'new'
    end
  end
  
  
  def show
    @user=User.find(params[:id])
    @friendship=current_user.friendships.find_by(friend_id: params[:id])
  end
  
  def index
    @users=User.all
  end
  
  def edit
    @user=User.find(params[:id])
  end
  
  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:success]="Your details were updated"
      redirect_to user_path(@user)
    else
      flash[:danger]="Something went wrong - please try again"
      render 'edit'
    end
  end
  
  def add_friend
    
  end
  
  def search
    @followers=User.search(params[:search_param]).uniq
    if @followers
      render partial: 'friends/lookup'
    else
      render status: :not_found, nothing: true
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
  
  def require_same_user
    if current_user != User.find(params[:id])
      flash[:danger]="You may only edit basic info for yourself"
      redirect_to user_path(User.find(params[:id]))
    end
  end
  
end
  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display:none;">
  <i class="fa fa-spinner fa-spin fa-2x"></i>Searching..
</div>

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <h3>Search Users</h3>
  <%= form_tag search_friends_path, remote: true, method: :get, id: "friend-lookup-form" do %>
  
  <div class="form-group row no-padding col-md-12">
    
    <div class="col-md-10">
      <%= text_field_tag :search_param, params[:search_param], placeholder: "first name, last name or email", 
                              autofocus: true, class: "form-control search-box input-lg" %>
    </div>
    
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn-lg btn-success") do %>
      <i class="fa fa-search"></i> Find
      <% end %>
    </div>

    <%= render 'common/spinner' %>
    
    <% if @followers %>
      <% if @followers.size > 0 %>
        <div id= "friend-lookup-results" class= "well results-block col-md-10">
          <table class="search-results-table col-md-12">
            <tbody>
              <% @followers.each do |u| %>
              <div style="border-bottom: 1px black dashed; padding-bottom: 5px;">
              <tr><%= u.first_name.capitalize+" "+u.last_name.capitalize %></tr></br>
              <tr><%= link_to "View #{u.first_name.capitalize}'s Profile",
                                                user_path(u), class: "btn-xs btn-success" %></tr></br>
              </div>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
      <p class="lead col-md-12">No matches</p>
      <% end %>
    <% end %>
          
      
    <div id="friend-lookup-errors"></div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StockTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "StockTracker", root_path, class:"navbar-brand" %> 
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            
            <% if logged_in? %>
            <li><%= link_to "My Profile", user_path(session[:user_id])  %></li>
            <% end %>
            
            <li><%= link_to "Stocks", stocks_path  %></li>
            <li><%= link_to "Users", users_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">
  <h3>Search Stocks</h3>
  <%= form_tag search_stocks_path, remote: true, method: :get, id: "stock-lookup-form" do %>
  
  <div class="form-group row no-padding col-md-12">
    
    <div class="col-md-10">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock Ticker, e.g. AAPL", autofocus: true,
                                                  class: "form-control search-box input-lg" %>
    </div>
    
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn-lg btn-success") do %>
      <i class="fa fa-search"></i> Find
      <% end %>
    </div>

    <%= render 'common/spinner' %>
    
    <% if @stock %>
      <div id= "stock-lookup-results" class= "well results-block">
        <strong>Symbol:</strong> <%= @stock.ticker %>
        <strong>Name:</strong> <%= @stock.name %>
        <strong>Price:</strong> <%= @stock.last_price %>
          
          <div style="margin: 10px;">
            <% if current_user.stocks.count < 10 && !current_user.stocks.include?(@stock) %>
            <%= link_to "Follow this Stock", user_stocks_path(user: current_user, stock_ticker: @stock.ticker, 
                        stock_id: @stock.id ? @stock.id: ''), class: "btn-xs btn-success", method: :post %>
            <% else %>
              <span class="label label-default">
              Cannot add this stock. You have already added
              <% if current_user.stocks.include?(@stock) %>
              this stock
              <% else %>
              the maximum number of stocks
              <% end %>
              </span>
            <% end %>
          </div>
      </div>
    <% end %>
      
      <div id="stock-lookup-errors"></div>
    </div>
  <% end %>
</div>

app/views/stocks/index.html.erb
<h1 align="center">All Stocks</h1></br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |f| %>
    <tr>
      <th><%= f.name %></th>
      <th><%= link_to f.ticker, stock_path(f) %></th>
      <th><%= f.last_price %></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/show.html.erb
<h1 class="well"> <%= @stock.name %> (<%= @stock.ticker %>) </h1>

<h3 style="color:slategrey; margin-left: 15px;"> Current Price: <%= @stock.last_price %>
  <% if current_user.stocks.include?(@stock) %>
  <%= link_to "Unfollow this Stock", 
              user_stock_path(@user_stock), 
              class: "btn-xs btn-danger btn-3", :method => :delete %>
  <% end %>
  <% if !current_user.stocks.include?(@stock) && current_user.stocks.count < 10 %>
  <%= link_to "Follow this Stock", user_stocks_path(user: current_user, stock_ticker: @stock.ticker, 
                      stock_id: @stock.id ? @stock.id: ''), class: "btn-xs btn-success btn-3", method: :post %>
  <% end %>
   
</h3>

app/views/users/edit.html.erb
<h1 align="Center">Hello <%= @user.first_name %>! Edit your details here</h1>

<div class="row jumbotron">

<%= form_for(@user) do |f| %>

<%= f.label :first_name %></br>
<%= f.text_field :first_name %></br></br>

<%= f.label :last_name %></br>
<%= f.text_field :last_name %></br></br>

<%= f.label :email %></br>
<%= f.text_field :email %></br></br>

<%= f.label :password %></br>
<%= f.text_field :password %></br></br>

<div class="btn-lg", style="margin-left:-17px;">
<%= f.submit "Submit" %>
</div>
</div>

<% end %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1></br>

<%= render 'friends/lookup' %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>E-mail</th>
      <th>Stocks</th>
      <th>Following?</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |f| %>
    <tr>
      <th><%= link_to (f.first_name.capitalize)+" "+(f.last_name.capitalize), user_path(f) %></th>
      <th><%= f.email %></th>
      <th><% f.stocks.each do |g| %>
          <%= link_to g.ticker+",", stock_path(g) %> 
          <% end %> </th>
      <th><% if current_user.friends.include?(f) %>
          Following
          <% end %></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1 align="Center">Sign Up to Stock Tracker!</h1>

<div class="row jumbotron">

<%= form_for(@user) do |f| %>

<%= f.label :first_name %></br>
<%= f.text_field :first_name %></br></br>

<%= f.label :last_name %></br>
<%= f.text_field :last_name %></br></br>

<%= f.label :email %></br>
<%= f.text_field :email %></br></br>

<%= f.label :password %></br>
<%= f.text_field :password %></br></br>

<div class="btn-lg", style="margin-left:-17px;">
<%= f.submit "Submit" %>
</div>
</div>

<% end %>

app/views/users/show.html.erb
<h1 align="Center"><%= @user.first_name.capitalize %>'s Profile</h1>

<div align="Center">
  <% if current_user==@user %>
  (<%= link_to "Update Basic Info", edit_user_path(@user) %>)
  <% end %>
</div></br>

  <% if current_user == @user %>
  <%= render 'stocks/lookup' %>
  <% end %>


<div align="center">
  <% if current_user.friends.include?(@user) && current_user != @user %>
  <%= link_to "Unfollow this person", friendship_path(@friendship), 
                    class: "btn-lg btn-primary", method: :delete %>
  <% end %>
  <% if !current_user.friends.include?(@user) && current_user != @user %>
  <%= link_to "Follow this person", friendships_path(user: current_user, friend_id: @user.id), 
              class: "btn-lg btn-primary", method: :post %>
  <% end %>
</div>


<h3 style="font-size: 1.5em;">Portfolio</h3>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
    </tr>
  </thead>
  <tbody>
    <% @user.stocks.each do |f| %>
    <tr>
      <th><%= f.name %></th>
      <th><%= link_to f.ticker, stock_path(f) %></th>
      <th><%= f.last_price %></th>
    </tr>
    <% end %>
  </tbody>
</table></br>


<h3 style="font-size: 1.5em;">Users Tracked</h3>

<div class="row col-md-12", style="padding:20px; margin-left: -5px; line-height: 50px;">
  <% @user.friends.each do |h| %>
  <div style="border-bottom: dashed 1px grey;">
    <%= link_to (h.first_name.capitalize)+" "+(h.last_name.capitalize), user_path(h) %>
  </div>  
  <% end %>
</div>

app/views/welcome/index.html.erb
<h2 align="Center">Welcome to the Stock Tracker</h2>

<div class="jumbotron", align="center">
  <% if session[:user_id] %>
  <div class="btn btn-lg">
  <%= link_to "Logout", logout_path, method: :delete %>
  <% else %>
  <div class="row">
  <div class= "btn btn-lg btn-1">
  <%= link_to "Login", login_path %>
  </div>
  <div class ="btn btn-lg btn-2">
  <%= link_to "Signup", signup_path %>
  </div>
  <% end %>
  </div>
  </div>
</div>